name = "forms"
workers_dev = true
compatibility_date = "2024-03-14"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "forms"

# Change to your test database
database_id = "d9378a34-9fe6-4232-9b8f-3322287d4cd0"
