name = "forms-api"
workers_dev = true
main = "build/worker/shim.mjs"
compatibility_date = "2024-03-14"

[build]
command = "worker-build --release"

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
fallthrough = false

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "forms"
migrations_dir = "../../migrations/"

# Change to your test database
database_id = "ea1e90b6-9ed0-44ec-8a82-05417fdcc638"
