name: Check Format and Code Quality
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches:
      - main
      - dev
    paths:
      - "src/**/**.rs"

jobs:
  check-fmt:
    uses: RustLangES/.github/workflows/templates/format.yml@main
    with:
      runs-on: ubuntu-latest
      name: Checks
      command: "--all --check"
      fmt-version: stable
      checkout-version: v4

  check-clippy:
    needs: [check-fmt]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: cargo check
        run: |
          cargo clippy -- -D warnings

  check-tests:
    needs: [check-clippy]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: cargo check
        run: |
          cargo test
