name: Deploy to production

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml"
      - "wrangler.toml"
      - "frontend/**"
      - "backend/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: checks
        run: |
          cargo fmt --all --check

  deploy:
    needs: [check]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        path:
          - backend
          - frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: pnpm/action-setup@v4
        if: ${{ matrix.path == 'frontend' }}
        with:
          version: 9
      - name: Install worker-build
        run: |
          cargo install worker-build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        # env:
          # YOUR_SECRET: ${{ secrets.YOUR_SECRET }}
          # YOUR_OTHER_SECRET: ${{ secrets.YOUR_OTHER_SECRET }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "${{ matrix.path }}"
          # secrets: |
          #   YOUR_SECRET
          #   YOUR_OTHER_SECRET
