name: Quality Gate
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches:
      - main
      - dev
    paths:
      - "src/**/**.rs"
      - "crates/**/**.rs"

jobs:
  quality-gate:
    uses: RustLangES/workflows/.github/workflows/quality-gate.yml@main
